title: 孤舟听雨
email: 862832617@qq.com
description: 岁月如歌，静听风雨。
description2: 孤舟行将江月冷，独酌无心夜风寒。
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title.html
  fragments:
    output: false  # 不生成独立页面，仅用于列表展示
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
baseurl: "zor666.me" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - other-plugin-1
  - other-plugin-2

