name: Deploy Pages

on:
  workflow_run:
    workflows: ["Generate articles.json"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 如果有构建步骤可在此添加

      # 这里用官方自带部署或 peaceiris/actions-gh-pages
      # 对于 username.github.io 仓库，建议直接用 main 分支作为 Pages 源，无需额外部署
      # 如果你有特殊构建需求，可在此添加 